# Generated by Django 4.1.7 on 2023-02-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_ad_image1_ad_image2_alter_ad_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.TextField(default='На рассмотрении'),
        ),
    ]
