# Generated by Django 4.1.7 on 2023-02-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_answer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
